# Generated by Django 5.1.1 on 2024-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_attendance_email_remove_attendance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
